log_name: HomePage

testcase:
  - element_info:
    find_type:
    operate_type: open
    operate_info: https://www.pypandas.cn/
    mathod: driver
  - element_info: 学习深度学习 →
    find_type: link_text
    operate_type: click
    operate_info:
    mathod: element
  - element_info: span[class="sub-text"]
    find_type: css_selector
    operate_type: click
    operate_info:
    mathod: element
  - element_info:
    find_type:
    operate_type: close
    operate_info:
    mathod: driver
