log_name: HomePage

testcase:
  - element_info:
    find_type:
    operate_type: open
    operate_info: https://music.163.com/
    mathod: driver
  - element_info: a[href*="/discover"]
    find_type: css_selectors
    operate_type:
    operate_info:
    mathod: get_element
  - element_info:
    find_type:
    operate_type: close
    operate_info:
    mathod: driver
