log_name: MusicHome

testcase:
  - element_info:
    find_type:
    operate_type: open
    operate_info: https://music.163.com/
    mathod: driver
  - element_info:
    find_type:
    operate_type: maximize_window
    operate_info:
    mathod: driver
  - element_info: 登录
    find_type: link_text
    operate_type: click
    operate_info:
    mathod: element
  - element_info: div>a[class="u-btn2 other"]
    find_type: css_selector
    operate_type: click
    operate_info:
    mathod: element
  - element_info: input[id="j-official-terms"]
    find_type: css_selector
    operate_type: click
    operate_info:
    mathod: element
  - element_info: div>a[class="u-btn2 u-btn2-2"]
    find_type: css_selector
    operate_type: click
    operate_info:
    mathod: element
  - element_info:
    find_type:
    operate_type: implicitly_wait
    operate_info: 5
    mathod: driver
  - element_info: div>input[class="j-phone txt u-txt"]
    find_type: css_selector
    operate_type: send_keys
    operate_info: 手机号
    mathod: element
  - element_info:
    find_type:
    operate_type: implicitly_wait
    operate_info: 5
    mathod: driver
  - element_info: div>input[class="j-pwd u-txt"]
    find_type: css_selector
    operate_type: send_keys
    operate_info: 密码
    mathod: element
  - element_info:
    find_type:
    operate_type: implicitly_wait
    operate_info: 10
    mathod: driver
  - element_info: div>a[class="j-primary u-btn2 u-btn2-2"]
    find_type: css_selector
    operate_type: click
    operate_info:
    mathod: element
  - element_info: div>div>div[class="head f-fl f-pr"]
    find_type: css_selector
    operate_type: move_to_element
    operate_info:
    mathod: mouse
  - element_info:
    find_type:
    operate_type: implicitly_wait
    operate_info: 10
    mathod: driver
  - element_info: a>i[class="icn icn-ex"]
    find_type: css_selector
    operate_type: click
    operate_info:
    mathod: element
#  - element_info:
#    find_type:
#    operate_type: close
#    operate_info:
#    mathod: driver
